title: "Berita-terbaru"
description: "Berita Premier League - Berita, informasi, dan update Bola terkini dari seluruh dunia"
url: "https://beritapremierleague.github.io/"  # URL utama situs
baseurl: "/berita-terbaru/"  # Jika situs Anda berada di subfolder GitHub Pages

# Pastikan timezone dan markdown sesuai
timezone: Asia/Jakarta  
markdown: kramdown  

# Plugin tambahan jika diperlukan
plugins:
  - jekyll-sitemap  # Otomatis buat sitemap.xml untuk SEO
  - jekyll-seo-tag  # Tambahkan meta tag SEO (opsional)

# Exclude file yang tidak perlu untuk mempercepat build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
